import { Quest, QuestDay } from "@/types";
import { computeQuestSummary } from "@/lib/quests/logic";

interface QuestDetailProps {
  quest: Quest;
  questDays: QuestDay[];
}

export function QuestDetail({ quest, questDays }: QuestDetailProps) {
  const ordered = [...questDays].sort((a, b) => a.dayIndex - b.dayIndex);
  const summary = computeQuestSummary(quest, questDays);

  return (
    <div className="sanctum-card border-[#333] p-4 shadow text-[0.95rem]">
      <div className="flex flex-col gap-1.5 sm:flex-row sm:items-baseline sm:justify-between">
        <div>
          <p className="text-[10px] uppercase tracking-[0.16em] text-[#c3a167] font-serif">Quest Log</p>
          <h4 className="text-sm font-semibold text-[#e0e0e0] font-serif tracking-wider">{quest.title}</h4>
          <p className="text-[0.78rem] text-[#7a7a7a]">Current streak: {summary.currentSuccessStreak} days</p>
        </div>
        <div className="flex gap-2 text-[0.8rem] text-[#e0e0e0]">
          <div className="rounded-md border border-[#333] bg-[#0c0c0c] px-2.5 py-1.5">Successes: {summary.totalSuccesses}</div>
          <div className="rounded-md border border-[#333] bg-[#0c0c0c] px-2.5 py-1.5">Fails: {summary.totalFails}</div>
        </div>
      </div>

      <div className="mt-3 space-y-2">
        {ordered.length === 0 && (
          <p className="text-[0.85rem] text-[#7a7a7a]">No days logged yet. The chronicle waits.</p>
        )}
        {ordered.map((day) => (
          <div
            key={day.date}
            className="rounded-md border border-[#333] bg-[#0c0c0c] px-3 py-2"
          >
            <div className="flex flex-wrap items-center justify-between gap-2 text-[0.85rem] text-[#e0e0e0]">
              <div className="flex items-center gap-2">
                <span className="rounded-full bg-[#111111] px-2 py-1 text-[10px] uppercase tracking-[0.12em] text-[#c3a167] font-serif">
                  Day {day.dayIndex + 1}
                </span>
                <span className="text-[11px] text-[#7a7a7a]">{day.date}</span>
              </div>
              <span
                className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${
                  day.status === "SUCCESS"
                    ? "border-[#c3a167] bg-[#1a1a1a] text-[#c3a167]"
                    : day.status === "FAIL"
                    ? "border-[#8a1c1c] bg-[#1a0c0c] text-[#f5d0d0]"
                    : "border-[#333] bg-[#0c0c0c] text-[#e0e0e0]"
                }`}
              >
                {day.status}
              </span>
            </div>
            {day.autogeneratedNarrative && (
              <p className="mt-1.5 text-[0.88rem] leading-relaxed text-[#e0e0e0]">{day.autogeneratedNarrative}</p>
            )}
            <p className="mt-1 text-[0.75rem] text-[#7a7a7a]">
              Vigor {formatDelta(day.vigorDelta)} · Resolve {formatDelta(day.resolveDelta)} · Corruption {formatDelta(day.corruptionDelta)}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function formatDelta(val: number) {
  if (val > 0) return `+${val}`;
  return `${val}`;
}
