import { Quest, QuestDay } from "@/types";
import { computeQuestSummary } from "@/lib/quests/logic";

interface QuestDetailProps {
  quest: Quest;
  questDays: QuestDay[];
}

export function QuestDetail({ quest, questDays }: QuestDetailProps) {
  const ordered = [...questDays].sort((a, b) => a.dayIndex - b.dayIndex);
  const summary = computeQuestSummary(quest, questDays);

  return (
    <div className="rounded-lg border border-slate-800 bg-slate-900 p-4 shadow">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-baseline sm:justify-between">
        <div>
          <p className="text-xs uppercase tracking-wide text-amber-400">Quest Log</p>
          <h4 className="text-lg font-semibold text-white">{quest.title}</h4>
          <p className="text-sm text-slate-300">Current streak: {summary.currentSuccessStreak} days</p>
        </div>
        <div className="flex gap-3 text-sm text-slate-200">
          <div className="rounded-md bg-slate-800 px-3 py-2">Successes: {summary.totalSuccesses}</div>
          <div className="rounded-md bg-slate-800 px-3 py-2">Fails: {summary.totalFails}</div>
        </div>
      </div>

      <div className="mt-4 space-y-3">
        {ordered.length === 0 && (
          <p className="text-sm text-slate-400">No days logged yet. The chronicle waits.</p>
        )}
        {ordered.map((day) => (
          <div
            key={day.date}
            className="rounded-md border border-slate-800 bg-slate-950 px-3 py-2"
          >
            <div className="flex flex-wrap items-center justify-between gap-2 text-sm text-slate-200">
              <div className="flex items-center gap-2">
                <span className="rounded-full bg-slate-800 px-2 py-1 text-[11px] uppercase tracking-wide text-amber-300">
                  Day {day.dayIndex + 1}
                </span>
                <span className="text-xs text-slate-400">{day.date}</span>
              </div>
              <span
                className={`rounded-full px-2 py-1 text-xs font-semibold ${
                  day.status === "SUCCESS"
                    ? "bg-emerald-700 text-white"
                    : day.status === "FAIL"
                    ? "bg-red-700 text-white"
                    : "bg-slate-700 text-white"
                }`}
              >
                {day.status}
              </span>
            </div>
            {day.autogeneratedNarrative && (
              <p className="mt-2 text-sm text-slate-300">{day.autogeneratedNarrative}</p>
            )}
            <p className="mt-1 text-xs text-slate-400">
              Vigor {formatDelta(day.vigorDelta)} · Resolve {formatDelta(day.resolveDelta)} · Corruption {formatDelta(day.corruptionDelta)}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function formatDelta(val: number) {
  if (val > 0) return `+${val}`;
  return `${val}`;
}
