import { Quest, QuestDay } from "@/types";
import { computeQuestSummary } from "@/lib/quests/logic";

interface QuestDetailProps {
  quest: Quest;
  questDays: QuestDay[];
}

export function QuestDetail({ quest, questDays }: QuestDetailProps) {
  const ordered = [...questDays].sort((a, b) => a.dayIndex - b.dayIndex);
  const summary = computeQuestSummary(quest, questDays);

  return (
    <div className="sanctum-card border-[#3e1d26] p-3 shadow">
      <div className="flex flex-col gap-1.5 sm:flex-row sm:items-baseline sm:justify-between">
        <div>
          <p className="text-[10px] uppercase tracking-wide text-amber-400">Quest Log</p>
          <h4 className="text-base font-semibold text-amber-100">{quest.title}</h4>
          <p className="text-[0.8rem] text-amber-200/80">Current streak: {summary.currentSuccessStreak} days</p>
        </div>
        <div className="flex gap-2 text-[0.8rem] text-amber-100">
          <div className="rounded-md border border-[#3e1d26] bg-[#0b0508]/80 px-2.5 py-1.5">Successes: {summary.totalSuccesses}</div>
          <div className="rounded-md border border-[#3e1d26] bg-[#0b0508]/80 px-2.5 py-1.5">Fails: {summary.totalFails}</div>
        </div>
      </div>

      <div className="mt-3 space-y-2">
        {ordered.length === 0 && (
          <p className="text-[0.85rem] text-amber-200/80">No days logged yet. The chronicle waits.</p>
        )}
        {ordered.map((day) => (
          <div
            key={day.date}
            className="rounded-md border border-[#3e1d26] bg-[#0b0508]/80 px-3 py-2"
          >
            <div className="flex flex-wrap items-center justify-between gap-2 text-[0.85rem] text-amber-100">
              <div className="flex items-center gap-2">
                <span className="rounded-full bg-[#1b0a0d] px-2 py-1 text-[10px] uppercase tracking-wide text-amber-300">
                  Day {day.dayIndex + 1}
                </span>
                <span className="text-[11px] text-amber-200/70">{day.date}</span>
              </div>
              <span
                className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${
                  day.status === "SUCCESS"
                    ? "border-emerald-700 bg-[#12251c] text-emerald-200"
                    : day.status === "FAIL"
                    ? "border-[#7a1d1d] bg-[#2b0f10] text-rose-200"
                    : "border-slate-700 bg-[#0f1117] text-slate-200"
                }`}
              >
                {day.status}
              </span>
            </div>
            {day.autogeneratedNarrative && (
              <p className="mt-2 text-[0.9rem] text-amber-100/90">{day.autogeneratedNarrative}</p>
            )}
            <p className="mt-1 text-[0.75rem] text-amber-200/70">
              Vigor {formatDelta(day.vigorDelta)} · Resolve {formatDelta(day.resolveDelta)} · Corruption {formatDelta(day.corruptionDelta)}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function formatDelta(val: number) {
  if (val > 0) return `+${val}`;
  return `${val}`;
}
